"""Contracts for the supplier CNY account ledger."""

from __future__ import annotations

CNY_DOCUMENT_TYPE_CONVERSION_PURCHASE = "cny_conversion_purchase"
CNY_DOCUMENT_TYPE_SUPPLIER_PAYMENT = "supplier_cny_payment"
CNY_DOCUMENT_TYPE_BANK_FEE = "bank_fee"
CNY_DOCUMENT_TYPE_OPENING_BALANCE = "opening_balance"
CNY_DOCUMENT_TYPE_ADJUSTMENT = "adjustment"
CNY_DOCUMENT_TYPES = {
    CNY_DOCUMENT_TYPE_CONVERSION_PURCHASE,
    CNY_DOCUMENT_TYPE_SUPPLIER_PAYMENT,
    CNY_DOCUMENT_TYPE_BANK_FEE,
    CNY_DOCUMENT_TYPE_OPENING_BALANCE,
    CNY_DOCUMENT_TYPE_ADJUSTMENT,
}

CNY_DOCUMENT_STATUS_PARSED = "parsed"
CNY_DOCUMENT_STATUS_NEEDS_REVIEW = "needs_review"
CNY_DOCUMENT_STATUS_POSTED = "posted"
CNY_DOCUMENT_STATUS_PARSE_ERROR = "parse_error"
CNY_DOCUMENT_STATUS_EXCLUDED = "excluded"
CNY_DOCUMENT_STATUSES = {
    CNY_DOCUMENT_STATUS_PARSED,
    CNY_DOCUMENT_STATUS_NEEDS_REVIEW,
    CNY_DOCUMENT_STATUS_POSTED,
    CNY_DOCUMENT_STATUS_PARSE_ERROR,
    CNY_DOCUMENT_STATUS_EXCLUDED,
}

CNY_DOCUMENT_SOURCE_CNY_ACCOUNT = "cny_account"
CNY_DOCUMENT_SOURCE_SUPPLIER_ORDER = "supplier_order"
CNY_DOCUMENT_SOURCES = {
    CNY_DOCUMENT_SOURCE_CNY_ACCOUNT,
    CNY_DOCUMENT_SOURCE_SUPPLIER_ORDER,
}

CNY_LEDGER_OPERATION_OPENING_BALANCE = "opening_balance"
CNY_LEDGER_OPERATION_CONVERSION_IN = "conversion_in"
CNY_LEDGER_OPERATION_SUPPLIER_PAYMENT_OUT = "supplier_payment_out"
CNY_LEDGER_OPERATION_CONVERSION_FEE = "conversion_fee"
CNY_LEDGER_OPERATION_TRANSFER_FEE = "transfer_fee"
CNY_LEDGER_OPERATION_ADJUSTMENT = "adjustment"
CNY_LEDGER_OPERATION_TYPES = {
    CNY_LEDGER_OPERATION_OPENING_BALANCE,
    CNY_LEDGER_OPERATION_CONVERSION_IN,
    CNY_LEDGER_OPERATION_SUPPLIER_PAYMENT_OUT,
    CNY_LEDGER_OPERATION_CONVERSION_FEE,
    CNY_LEDGER_OPERATION_TRANSFER_FEE,
    CNY_LEDGER_OPERATION_ADJUSTMENT,
}

CNY_LEDGER_OPERATION_STATUS_POSTED = "posted"
CNY_LEDGER_OPERATION_STATUS_BLOCKED = "blocked"
CNY_LEDGER_OPERATION_STATUS_NEEDS_REVIEW = "needs_review"
CNY_LEDGER_OPERATION_STATUS_SKIPPED = "skipped"
CNY_LEDGER_OPERATION_STATUSES = {
    CNY_LEDGER_OPERATION_STATUS_POSTED,
    CNY_LEDGER_OPERATION_STATUS_BLOCKED,
    CNY_LEDGER_OPERATION_STATUS_NEEDS_REVIEW,
    CNY_LEDGER_OPERATION_STATUS_SKIPPED,
}

CNY_CALC_STATUS_OK = "ok"
CNY_CALC_STATUS_NO_SUPPLIER_PAYMENT = "no_supplier_payment_yet"
CNY_CALC_STATUS_MISSING_OPENING_BALANCE = "missing_opening_balance"
CNY_CALC_STATUS_INSUFFICIENT_BALANCE = "insufficient_cny_balance"
CNY_CALC_STATUS_PAYMENT_NOT_LINKED = "payment_document_not_linked_to_order"
CNY_CALC_STATUS_PARSE_ERROR = "parse_error"
CNY_CALC_STATUS_AMBIGUOUS_ALLOCATION = "ambiguous_allocation"
CNY_CALC_STATUS_DOCUMENT_DATE_MISSING = "document_date_missing"
CNY_CALC_STATUS_NEEDS_REVIEW = "needs_review"
CNY_CALC_STATUSES = {
    CNY_CALC_STATUS_OK,
    CNY_CALC_STATUS_NO_SUPPLIER_PAYMENT,
    CNY_CALC_STATUS_MISSING_OPENING_BALANCE,
    CNY_CALC_STATUS_INSUFFICIENT_BALANCE,
    CNY_CALC_STATUS_PAYMENT_NOT_LINKED,
    CNY_CALC_STATUS_PARSE_ERROR,
    CNY_CALC_STATUS_AMBIGUOUS_ALLOCATION,
    CNY_CALC_STATUS_DOCUMENT_DATE_MISSING,
    CNY_CALC_STATUS_NEEDS_REVIEW,
}

CNY_LEDGER_PARSER_VERSION = "supplier_cny_ledger_parser_v1"
CNY_LEDGER_CONTRACT_NAME = "sheet_vitrina_v1_cny_ledger"

CNY_LEDGER_ALLOWED_EXTENSIONS = {".pdf"}
CNY_LEDGER_CONTENT_TYPE = "application/pdf"
