"""Contracts and constants for supplier invoice shipment registry."""

from __future__ import annotations

LINE_TYPE_PRODUCT = "product"
LINE_TYPE_EXTRA = "extra"

PRODUCT_TYPE_CLEAR = "clear"
PRODUCT_TYPE_ANTI_SPY = "anti_spy"
PRODUCT_TYPE_MATTE = "matte"

MATCH_STATUS_MATCHED = "matched"
MATCH_STATUS_MATCHED_BY_COMPATIBILITY = "matched_by_compatibility"
MATCH_STATUS_MATCHED_BY_BARCODE = "matched_by_barcode"
MATCH_STATUS_UNMATCHED = "unmatched"
MATCH_STATUS_AMBIGUOUS = "ambiguous"
MATCH_STATUS_EXTRA = "extra"
MATCH_STATUSES_WITH_AUTHORITATIVE_NM_ID = {
    MATCH_STATUS_MATCHED,
    MATCH_STATUS_MATCHED_BY_COMPATIBILITY,
    MATCH_STATUS_MATCHED_BY_BARCODE,
}

PRICE_CONFORMITY_STATUS_MATCHED = "matched"
PRICE_CONFORMITY_STATUS_MISMATCHED = "mismatched"
PRICE_CONFORMITY_STATUS_SKU_NOT_FOUND = "sku_not_found"
PRICE_CONFORMITY_STATUS_REFERENCE_PRICE_MISSING = "reference_price_missing"
PRICE_CONFORMITY_STATUS_INVOICE_PRICE_MISSING = "invoice_price_missing"
PRICE_CONFORMITY_STATUS_NOT_CHECKED = "not_checked"
PRICE_CONFORMITY_STATUSES = {
    PRICE_CONFORMITY_STATUS_MATCHED,
    PRICE_CONFORMITY_STATUS_MISMATCHED,
    PRICE_CONFORMITY_STATUS_SKU_NOT_FOUND,
    PRICE_CONFORMITY_STATUS_REFERENCE_PRICE_MISSING,
    PRICE_CONFORMITY_STATUS_INVOICE_PRICE_MISSING,
    PRICE_CONFORMITY_STATUS_NOT_CHECKED,
}

PRICE_CONFORMITY_CHECK_MODE_INITIAL_PARSE = "initial_parse"
PRICE_CONFORMITY_CHECK_MODE_MANUAL_RECHECK = "manual_recheck"
PRICE_CONFORMITY_CHECK_MODE_MIGRATION_BACKFILL = "migration_backfill"
PRICE_CONFORMITY_CHECK_MODE_NOT_CHECKED = "not_checked"
PRICE_CONFORMITY_CHECK_MODES = {
    PRICE_CONFORMITY_CHECK_MODE_INITIAL_PARSE,
    PRICE_CONFORMITY_CHECK_MODE_MANUAL_RECHECK,
    PRICE_CONFORMITY_CHECK_MODE_MIGRATION_BACKFILL,
    PRICE_CONFORMITY_CHECK_MODE_NOT_CHECKED,
}

SHIPMENT_STATUS_ALL_MATCHED = "all_matched"
SHIPMENT_STATUS_HAS_UNMATCHED = "has_unmatched"
SHIPMENT_STATUS_MANUAL_OVERRIDE = "manual_override"
SHIPMENT_STATUS_CHECKSUM_ERROR = "checksum_error"

ORDER_STATUS_PRODUCTION = "production"
ORDER_STATUS_IN_TRANSIT = "in_transit"
ORDER_STATUS_ACCEPTED_FF = "accepted_ff"
ORDER_STATUS_DEFAULT = ORDER_STATUS_PRODUCTION
ORDER_STATUSES = {
    ORDER_STATUS_PRODUCTION,
    ORDER_STATUS_IN_TRANSIT,
    ORDER_STATUS_ACCEPTED_FF,
}
ORDER_STATUS_LABELS_RU = {
    ORDER_STATUS_PRODUCTION: "На производстве",
    ORDER_STATUS_IN_TRANSIT: "В пути",
    ORDER_STATUS_ACCEPTED_FF: "Принято на ФФ",
}

DEFAULT_SUPPLIER_NAME = "HanShang Technology"

SUPPLIER_INVOICE_PARSER_VERSION = "supplier_invoice_parser_v2"
TRADE_DOCUMENT_CONTRACT_PARSER_VERSION = "contract_metadata_parser_v2"

SUPPLIER_INVOICE_CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

TRADE_DOCUMENT_TYPE_CONTRACT = "contract"
TRADE_DOCUMENT_TYPE_INVOICE = "invoice"
TRADE_DOCUMENT_TYPES = {
    TRADE_DOCUMENT_TYPE_CONTRACT,
    TRADE_DOCUMENT_TYPE_INVOICE,
}

TRADE_DOCUMENT_SOURCE_SETTINGS_UPLOAD = "settings_upload"
TRADE_DOCUMENT_SOURCE_SUPPLIER_SHIPMENT_PARSE = "supplier_shipment_parse"
TRADE_DOCUMENT_SOURCE_MIGRATION_EXISTING_SUPPLIER_INVOICE = "migration_existing_supplier_invoice"
TRADE_DOCUMENT_SOURCES = {
    TRADE_DOCUMENT_SOURCE_SETTINGS_UPLOAD,
    TRADE_DOCUMENT_SOURCE_SUPPLIER_SHIPMENT_PARSE,
    TRADE_DOCUMENT_SOURCE_MIGRATION_EXISTING_SUPPLIER_INVOICE,
}

TRADE_DOCUMENT_STATUS_ACTIVE = "active"
TRADE_DOCUMENT_STATUS_ARCHIVED = "archived"
TRADE_DOCUMENT_STATUSES = {
    TRADE_DOCUMENT_STATUS_ACTIVE,
    TRADE_DOCUMENT_STATUS_ARCHIVED,
}

TRADE_DOCUMENT_LINK_SOURCE_OPERATOR = "operator"
TRADE_DOCUMENT_LINK_SOURCE_SUPPLIER_SHIPMENT_AUTO = "supplier_shipment_auto"
TRADE_DOCUMENT_LINK_SOURCE_MIGRATION = "migration"

TRADE_DOCUMENT_ALLOWED_EXTENSIONS = {".pdf", ".jpg", ".jpeg", ".png", ".xlsx"}
TRADE_DOCUMENT_CONTENT_TYPES_BY_EXTENSION = {
    ".pdf": "application/pdf",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".xlsx": SUPPLIER_INVOICE_CONTENT_TYPE,
}

NOMENCLATURE_BARCODE_SOURCE_MANUAL = "manual"
NOMENCLATURE_BARCODE_SOURCE_WB_CONTENT = "wb_content"
NOMENCLATURE_BARCODE_SOURCE_WB_SUPPLIES_WEAK = "wb_supplies_weak"
NOMENCLATURE_BARCODE_SOURCE_MISSING = "missing"
NOMENCLATURE_BARCODE_SOURCE_ERROR = "error"
NOMENCLATURE_BARCODE_SOURCES = {
    NOMENCLATURE_BARCODE_SOURCE_MANUAL,
    NOMENCLATURE_BARCODE_SOURCE_WB_CONTENT,
    NOMENCLATURE_BARCODE_SOURCE_WB_SUPPLIES_WEAK,
    NOMENCLATURE_BARCODE_SOURCE_MISSING,
    NOMENCLATURE_BARCODE_SOURCE_ERROR,
}

NOMENCLATURE_BARCODE_STATUS_READY = "ready"
NOMENCLATURE_BARCODE_STATUS_MISSING = "missing"
NOMENCLATURE_BARCODE_STATUS_MANUAL = "manual"
NOMENCLATURE_BARCODE_STATUS_MULTIPLE = "multiple"
NOMENCLATURE_BARCODE_STATUS_SYNC_ERROR = "sync_error"
NOMENCLATURE_BARCODE_STATUS_TOKEN_MISSING = "token_missing"
NOMENCLATURE_BARCODE_STATUSES = {
    NOMENCLATURE_BARCODE_STATUS_READY,
    NOMENCLATURE_BARCODE_STATUS_MISSING,
    NOMENCLATURE_BARCODE_STATUS_MANUAL,
    NOMENCLATURE_BARCODE_STATUS_MULTIPLE,
    NOMENCLATURE_BARCODE_STATUS_SYNC_ERROR,
    NOMENCLATURE_BARCODE_STATUS_TOKEN_MISSING,
}
