"""Contracts for supplier order financial documents."""

from __future__ import annotations

FINANCIAL_DOCUMENT_TYPE_LOGISTICS_QUOTE = "logistics_quote"
FINANCIAL_DOCUMENT_TYPE_LOGISTICS_INVOICE = "logistics_invoice"
FINANCIAL_DOCUMENT_TYPE_CUSTOMS_DECLARATION = "customs_declaration"
FINANCIAL_DOCUMENT_TYPE_BANK_CONTROL_STATEMENT = "bank_control_statement"
FINANCIAL_DOCUMENT_TYPE_BANK_TRANSFER_APPLICATION = "bank_transfer_application"
FINANCIAL_DOCUMENT_TYPE_BANK_FEE_STATEMENT = "bank_fee_statement"
FINANCIAL_DOCUMENT_TYPE_PACKING_LIST = "packing_list"
FINANCIAL_DOCUMENT_TYPES = {
    FINANCIAL_DOCUMENT_TYPE_LOGISTICS_QUOTE,
    FINANCIAL_DOCUMENT_TYPE_LOGISTICS_INVOICE,
    FINANCIAL_DOCUMENT_TYPE_CUSTOMS_DECLARATION,
    FINANCIAL_DOCUMENT_TYPE_BANK_CONTROL_STATEMENT,
    FINANCIAL_DOCUMENT_TYPE_BANK_TRANSFER_APPLICATION,
    FINANCIAL_DOCUMENT_TYPE_BANK_FEE_STATEMENT,
    FINANCIAL_DOCUMENT_TYPE_PACKING_LIST,
}

FINANCIAL_DOCUMENT_PARSE_STATUS_PARSED = "parsed"
FINANCIAL_DOCUMENT_PARSE_STATUS_NEEDS_REVIEW = "needs_review"
FINANCIAL_DOCUMENT_PARSE_STATUS_CONFIRMED = "confirmed"
FINANCIAL_DOCUMENT_PARSE_STATUS_EXCLUDED = "excluded"
FINANCIAL_DOCUMENT_PARSE_STATUS_PARSE_ERROR = "parse_error"
FINANCIAL_DOCUMENT_PARSE_STATUSES = {
    FINANCIAL_DOCUMENT_PARSE_STATUS_PARSED,
    FINANCIAL_DOCUMENT_PARSE_STATUS_NEEDS_REVIEW,
    FINANCIAL_DOCUMENT_PARSE_STATUS_CONFIRMED,
    FINANCIAL_DOCUMENT_PARSE_STATUS_EXCLUDED,
    FINANCIAL_DOCUMENT_PARSE_STATUS_PARSE_ERROR,
}

FINANCIAL_DOCUMENT_ALLOWED_EXTENSIONS = {".pdf", ".xls", ".xlsx"}
FINANCIAL_DOCUMENT_CONTENT_TYPE = "application/pdf"

FINANCIAL_DOCUMENT_PARSER_VERSION = "supplier_financial_document_parser_v7"
CUSTOMS_ANNEX_ITEMS_PARSER_VERSION = "supplier_customs_annex_items_v2"

FX_RATE_SOURCE_CBR = "cbr"
FX_RATE_STATUS_OK = "ok"
FX_RATE_STATUS_PENDING = "rate_pending"
FX_RATE_STATUS_MISSING = "fx_rate_missing"

EXPENSE_CATEGORY_DELIVERY = "delivery_cost"
EXPENSE_CATEGORY_CUSTOMS_PAYMENTS = "customs_payments_and_fees"
EXPENSE_CATEGORY_ECOLOGICAL_FEE = "ecological_fee"
EXPENSE_CATEGORY_BROKERAGE = "brokerage_services"
EXPENSE_CATEGORY_COMPANY_COMMISSION = "company_commission"
EXPENSE_CATEGORY_INSURANCE = "insurance"
EXPENSE_CATEGORY_PACKAGING = "packaging"
EXPENSE_CATEGORY_PERMISSION_DOCS = "additional_permission_docs"
EXPENSE_CATEGORY_EXPORT_DOCS = "export_docs_possible"
EXPENSE_CATEGORY_BORDER_EXPEDITION = "border_expedition"
EXPENSE_CATEGORY_DOMESTIC_TRANSPORT = "domestic_transport"
EXPENSE_CATEGORY_CUSTOMS_FEE_1010 = "customs_fee_1010"
EXPENSE_CATEGORY_IMPORT_DUTY_2010 = "import_duty_2010"
EXPENSE_CATEGORY_IMPORT_VAT_5010 = "import_vat_5010"
EXPENSE_CATEGORY_BANK_TRANSFER_FEE = "bank_transfer_fee"
EXPENSE_CATEGORY_CURRENCY_CONTROL_FEE = "currency_control_fee"
EXPENSE_CATEGORY_CURRENCY_CONTROL_VAT = "currency_control_vat"
EXPENSE_CATEGORY_OTHER_BANK_FEE = "other_bank_fee"

EXPENSE_LINE_STATUS_PARSED = "parsed"
EXPENSE_LINE_STATUS_POSSIBLE_NOT_INCLUDED = "possible_not_included"
EXPENSE_LINE_STATUS_NEEDS_REVIEW = "needs_review"
